services:
  - docker

before_install:
- docker pull ompcloud/ompcloud-test:latest
- docker run -d -t --name ompcloud-test ompcloud/ompcloud-test:latest /sbin/my_init

script:
- docker exec -t ompcloud-test /opt/ompcloud/script/ompcloud-updatetools.sh

after_script:
- docker exec -t ompcloud-test /opt/ompcloud/script/ompcloud-quicktests.sh -q
